# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
